name: Price Scraper Workflow

on:
  schedule:
    - cron: "0 12 * * *" # Ejecuta todos los días a las 12:00 UTC (09:00 ARG)
  workflow_dispatch:

jobs:
  scrape-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run price scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          SAVE_TO_SUPABASE: "true"
          DEBUG: "true"
        run: |
          echo "Running price scraper..."
          python main.py

      - name: Trigger frontend revalidation
        env:
          REVALIDATION_TOKEN: ${{ secrets.REVALIDATION_TOKEN }}
        run: |
          curl -X POST "https://argentina-cara-fe.vercel.app/api/revalidate" \
            -H "Content-Type: application/json" \
            -d "{\"secret\":\"$REVALIDATION_TOKEN\"}"
